[package]
name = "microbit_sandbox"
version = "0.1.0"
authors = ["Henrik Böving <hargonix@gmail.com>"]
edition = "2018"

[dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7.0"
panic-halt = "0.2.0"
rtt-target = { version = "0.3.1", features = ["cortex-m"] }
panic-rtt-target = { version = "0.1.2", features = ["cortex-m"] }
embedded-hal = "0.2.7"
nrf52833-hal = "0.15.0"
microbit-v2 = "0.12.0"

[[bin]]
name = "microbit_sandbox"
test = false
bench = false